services:
  main:
    container_name: cashbook-eh1
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        APP_VERSION: ${APP_VERSION:-dev}
    image: silencezhoudev/cashbook:latest
    restart: always
    # network_mode: "host"
    env_file:
      - ../.env
    environment:
      APP_VERSION: ${APP_VERSION:-dev}
      NUXT_APP_VERSION: ${APP_VERSION:-dev}
      NUXT_PUBLIC_APP_VERSION: ${APP_VERSION:-dev}
      DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@cashbook_db:5432/cashbook?schema=public"
    volumes:
      - ./data:/app/data
    ports:
      - 9090:9090
  db:
    container_name: cashbook_db
    image: postgres:17.4-alpine3.21
    restart: always
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cashbook"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: cashbook
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 6432:5432

